- id: "1732593887276"
  alias: Holiday Mantle Lights - On
  description: ""
  triggers:
    - trigger: time
      at: "18:00:00"
  conditions:
    - condition: not
      conditions:
        - condition: state
          entity_id: alarm_control_panel.home_alarm
          state: armed_vacation
  actions:
    - type: turn_on
      device_id: badb29c5b3232dbb20cfc8d6b3ffa21a
      entity_id: f0a936abb4128ecc9c37b6661b588beb
      domain: switch
  mode: single
- id: "1732594009144"
  alias: Holiday Mantle Lights - Off
  description: ""
  triggers:
    - trigger: time
      at: "23:50:00"
  conditions: []
  actions:
    - type: turn_off
      device_id: badb29c5b3232dbb20cfc8d6b3ffa21a
      entity_id: f0a936abb4128ecc9c37b6661b588beb
      domain: switch
  mode: single
