apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: db-password
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: root-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "db-root-pass"
spec:
  refreshInterval: "30m"
  target:
    name: db-root-pass
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: "root-password"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "db-user-pass"
spec:
  refreshInterval: "30m"
  target:
    name: db-user-pass
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: "db-password"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-config
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: wavelog
  target:
    name: db-config
    template:
      engineVersion: v2
      data:
        MARIADB_USER: wavelog
        MARIADB_PASSWORD: "{{ .db_password }}"
        MARIADB_DATABASE: wavelog
        MARIADB_ROOT_PASSWORD: "{{ .root_password }}"
  data:
    - secretKey: db_password
      remoteRef:
        key: db-user-pass
        property: password
    - secretKey: root_password
      remoteRef:
        key: db-root-pass
        property: password
