---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: user-data
spec:
  storageClassName: freenas-iscsi-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
