apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wavelog-config
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: wavelog
  target:
    name: wavelog-config
    template:
      engineVersion: v2
      templateFrom:
        - target: Data
          configMap:
            name: wavelog-config-tmpl
            items:
              - key: config.php
                templateAs: Values
              - key: database.php
                templateAs: Values
  data:
    - secretKey: qrz_username
      remoteRef:
        key: wavelog-secrets
        property: qrz_username
    - secretKey: qrz_password
      remoteRef:
        key: wavelog-secrets
        property: qrz_password
    - secretKey: db_username
      remoteRef:
        key: db-config
        property: MARIADB_USER
    - secretKey: db_password
      remoteRef:
        key: db-config
        property: MARIADB_PASSWORD
    - secretKey: db_name
      remoteRef:
        key: db-config
        property: MARIADB_DATABASE
