apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tailscale

resources:
  - namespace.yaml
  - sealed-secret.yaml

helmCharts:
  - name: tailscale-subnet-router
    releaseName: subnet-router
    namespace: subnet-router
    version: 1.2.1
    repo: https://gtaylor.github.io/helm-charts
    valuesInline:
      image:
        repository: ghcr.io/tailscale/tailscale
        tag: v1.76
      tailscale:
        routes:
          - 10.96.0.0/12
          - 10.10.0.35/32
          - 10.10.0.1/32
          - 10.10.98.0/24
