---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: unpackerr-arr-keys
  namespace: unpackerr
spec:
  encryptedData:
    radarr_api_key: AgBDw4zaHBMr+omghhYkhI2UYbQMTevFH4KMhsvBb/Vv5FY4GSMs1bcqnn5H2rv5Oq3Gt2fM+sK6lR3fIC1F3krESPsHMYs2FE0O/nnAryM31TLVAyxCMJSlDndEixi3/cYA5kp87Dj5EEw6R8zRKcDOSktacrCE8emE/z7apHe0IdmbeZSdlarCIpZhOKL7CzcJRcwRFzjlHZ1GIrw/oHWkMQIcpi7RfrZfrjQnav7arkwORik9u1UHbVHq2uBAiJRypJRk29/QgccYDQt1OYfV5AEIo19IIFPg8i5x5zmlyP+k7J5fxBKYjLeRd2KdSXhDsEF4fOQnwSLoUj0+n5ugd6I8PMgxNrGTy96sSFR1YbrSMoCsmzl2+cg70CE/rkhBvVul3q1fOdktSKD5k3AN3nE58U+x7t78xTvW5D//Qwr+K4JHry8ofWVNGBvUHfsBNE97pbrrgjvYbPEBQZpY+RSKbs/aWCbe/5DgbBUnu1GYX4S1NEM4vEUTemQycj+uHZqLUpb12tDPt2cvpkWPGQZFsHitRpxhT47/XPAiJ9DrjOKS49HkmxnWWNNVr5f5ijpf9fwjI8TXz27Ry13zktmxTDkgdWkuqZOhucINgyew2ApLs+Vo2VY0cgpGDX1QMaGYed26kLCixs8jY2Bu4JavW7OSYH06c07xG8IsVE1qoSJzfP8NDSL4ORQEJzjXyHZMBIXjI3DcNFfIM6I8IEA6o8GdLJIHQeIZC6wuVg==
    sonarr_api_key: AgBqNzzHZbW6D4KtOl47UNZObTeASjLPcqZ3Htg1FBBLelHu1yvUWpiSqa1uVjZWktBIFBglgLKb9OHRS7pt5ytQTPudM/3qxgNs61Orb72MfR1VtVjOqyNqTlmsqmBchEY+gLMO2As28+JHSJE7H5UvF7tHXLM+yLQdxdZSv8LQgmjsXCWWfilGxAibrPCXcib4xu88TCtu9xGG5Djqp5aOB1rlYc8oJyhg7NOhR/fsjvIkztmEECK0IP6s3b8V6zWSCiHN9T8VO2/IpaNfrXLfEcIcYHTy4hNst9MM4smWQB1hSZs3qfUjiRgg9mS2HHCh/MeqqmZMS3PmI0IMveQTueuaIcqfr2cd58rx+l7+qXEhc8zWhY8/cdNTqE1XVFA4MU15MF+3p2okiVltb+IoaWwKIj7/iNz7XBHtOQ8qJ+3ka08iaAk6hXVwQyRpD068cVCnkg6RQXtEf8SWLjZlnXnmK07jWqzFZYNQLIGmJnHpqZZKN+Nvc8JFr92J4nrT1hrmTwKamGq8Oi6WPB6wyUuRguaxWBxoEmwupTEy7PHi+WpK9TIWKCs5KqlFvVrhh+2gh9Bt8VMlJ2k3H1ZbTtstNKmt6b/fhPQkM+ZRgQzmu86FMCPx9Ik4Tf4E8uvwgrfiFA25UDb+IkFYQlOmmzjzCbd4nNXq2CmnZD8pGnZLGs6Abi1YFB6DfpyxYB0W0X9gZaaQ1VRwmfZMXoTI6lkilUaWHTXWyplLNWc+FQ==
  template:
    metadata:
      name: unpackerr-arr-keys
      namespace: unpackerr
