apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: yardwhisper

resources:
  - namespace.yaml
  - postgres.yaml
  - pvc.yaml
  - caddyfile-configmap.yaml
  - collector-configmap.yaml
  - sealedsecret-yardwhisper-secrets.yaml
  - sealedsecret-yardwhisper-collector-secrets.yaml
  - sealedsecret-yardwhisper-adminer-basic-auth.yaml
  - sealedsecret-yardwhisper-ghcr-pull-secret.yaml

helmCharts:
  - name: app-template
    releaseName: yardwhisper
    namespace: yardwhisper
    version: 4.3.0
    repo: https://bjw-s-labs.github.io/helm-charts
    valuesFile: values.yaml
