apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: yardwhisper-ghcr-pull-secret
  namespace: yardwhisper
spec:
  encryptedData:
    .dockerconfigjson: AgAsuDll0YYDSwKD4XBLuyeO1BerJPkfcDtU6BERNnXivmYQig5Mc5mkLGqf+psb3r5Z9zM2hgRls/x/AZAx95HmyMfQfJrIoyrs2jzdrKseiwcqsge9D9O+prdKfYG2/e9nVzNY+hzw1uL2ILoX6+Clgaz3tRBjFP+KeMK15d/QlMJfjr0DVbDFIpUCt7Ip/n+6yKCrLlwfYoYhdJG/jRBglA19VFUSIzrpBo+Pn1WMEWgq92vlCN+hnNN4DLHQAGCkH+hieKpzQy6UteKrPI5c7/78EvNI+WdZePJjif8Ii1qNhA9Qa+rwLQ5+DoiDQpSHXr8a3MtgqsNm9L2ZjpYDUPTRW9mWfxMHcv/m/eE4zlukwzEeQnDLZu9F1eaqMZaXm9MeVpE8+DUI6Mtt+To3gDqtl7JTQUkWY7y8pH1L2fbqRPfE7fhwoVgW2Cyz73Fw/1qnzwEiTdMmoHie4fSh+mwgf0RpdDiq9jfuW3RlWyIGReZCmywiKqpuU26rOuT3gErN6AXYcghYP0G+hPrp6mBIf8LwqGE3JQDzujEoYgAe/NLAlzJeTyvorcVQaspZmqdwqTEYxIhLAsmYSn7PifUaJAOgd87wpk/Chvsa53Rr5oGmQN/Y8fxz+2zDBjb1ITkeOIF+TacFRXSQh4yFNN/yI3D7eG0IhK8wtKvGaZjXPyPSDORhFS1a6yMgP3qC6SbHbcea59H4DG3U3TouTn4R8QBs4QkUbt3xLLz+HCjj6TXaUEDz1q0D9gRL4gHhRSclGsRdmwqP2nZV2uBDnR23ld/YOcZo0Kxiagr66K2hjNwwdjvJNOG0Ox+6PyG+zV5wbt0rOEWFq9zQEwZZzHf1s3T6mhT6YHzBflnHUFybQSoqLnb1eo7K62ZOENTv4ok+iwLW6O90ncogo2RcRNgNsOJFpBvCzA3hSeoOZCzW2HfjY6ZP0q+iFEL1C3E=
  template:
    metadata:
      creationTimestamp: null
      name: yardwhisper-ghcr-pull-secret
      namespace: yardwhisper
    type: kubernetes.io/dockerconfigjson

