apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: yardwhisper-adminer-basic-auth
  namespace: yardwhisper
spec:
  encryptedData:
    auth: AgBeJ7hGqQX1FREzLI1hXd+eMEjx2LDJURiDYzNxXyiri7L7OpNiVF7WMcYkrrqgmkVtyUmiEjqSPHeqmVMpFMTdjhz/TZckCUzBMxwS4nQoQNLmSEk8bmnFS1V9ejGmre/GENAbe8ESSo0Nkcxs2JSCQJqT411RmFcPzv/ZQOHnqYfHmOsfQq0Hnksj8z4ObvQl3+fG6HsMHPS70KjTUWF7x3rvWpDOm51yJasQgOSJttMcbg+brkrCs8HHOSfnoDzvvFV4nD6T+aAnRCmtxoOm1knDZwUxfd95XZBggtEDTmftDLjeXiIXsIGukYqBAwRNf91dqS9I+cs9a5wXGF4jUJlP4tc0a5zX855KwmHZ1u2Pzk8MNWC4IFNzUi6SgT7PnFb7FRmHnXuwb5L4bgclxfk57A7wG6cSkgQoYdJ1vnYnbWc16HeCs9t4uc8ggwBAeq5MpvcRkjhlEUBhZesqMO9quJ6ibnreG/IMnzz813q3UhloimM7nvfNh7DhnM2nWrwUryy2kysZ88Uurt1lkipHh40qFJl1dNpqrjKOaFyezZJg37ckfHbXxA7IoUq1B/ZKUfCsrH2l7hI7fe7jApcXHpBBTp3byRd6h9WnHPvKI5NfsBwtsIWVu0oYzLYqpc/JeMWErs3delaAidoPFEKK/wINv6bE6PMza05likWhQWTOWNGDE3IhUy5dbZlswWVIl+3zGTfZ80SftiJOhAWDg/nfSjNcomEWuPC+jP+/jT8Dg3NTCmF4uzFmZ/cjuOvYYydtn48dBSae+/lnK1pkEw==
  template:
    metadata:
      creationTimestamp: null
      name: yardwhisper-adminer-basic-auth
      namespace: yardwhisper

