apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mqtt

resources:
  - namespace.yaml

helmCharts:
  - name: mosquitto
    releaseName: mosquitto
    namespace: mqtt
    version: 4.8.2
    repo: https://k8s-at-home.com/charts
    valuesInline:
      image:
        tag: '2.0.18'
patches:
  - target:
      kind: Service
      name: mosquitto
    patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer
      - op: replace
        path: /spec/externalTrafficPolicy
        value: Local
      - op: add
        path: /metadata/annotations
        value:
          external-dns.alpha.kubernetes.io/hostname: mqtt.herrington.services
      - op: add
        path: /metadata/annotations
        value:
          uptimekuma.io/monitor: "true"
          uptimekuma.io/name: "KMS"
          uptimekuma.io/type: "port"
          uptimekuma.io/interval: "120"
          uptimekuma.io/hostname: mqtt.herrington.services
          uptimekuma.io/port: "1883"