apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mdbo

resources:
  - namespace.yaml

helmCharts:
  - name: mariadb-operator
    releaseName: mdbo
    namespace: mdbo
    version: 0.29.0
    includeCRDs: true
    repo: https://helm.mariadb.com/mariadb-operator
    valuesInline:
      metrics:
        enabled: false
