apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: readarr-config
  namespace: piracy
  labels:
    app.kubernetes.io/instance: readarr
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: readarr
    app.kubernetes.io/version: v0.1.0.715
    helm.sh/chart: readarr-6.4.2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: freenas-iscsi-ssd-csi
  resources:
    requests:
      storage: 1Gi
