apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: omniroute

resources:
  - namespace.yaml
  - redis.yaml
  - sealed-omniroute-secrets.yaml

helmCharts:
  - name: app-template
    releaseName: omniroute
    namespace: omniroute
    version: 4.6.2
    repo: https://bjw-s-labs.github.io/helm-charts
    valuesFile: values.yaml
