apiVersion: apps/v1
kind: Deployment
metadata:
  name: barcode-api
spec:
  template:
    spec:
      containers:
        - name: app
          env:
            - name: ba_log_json
              value: "True"
            - name: ba_log_level
              value: debug
            - name: ba_discogs_token
              valueFrom:
                secretKeyRef:
                  name: barcode-api-secrets
                  key: discogs_token
            - name: ba_spotify_client_id
              valueFrom:
                secretKeyRef:
                  name: barcode-api-secrets
                  key: spotify_client_id
            - name: ba_spotify_client_secret
              valueFrom:
                secretKeyRef:
                  name: barcode-api-secrets
                  key: spotify_client_secret
