apiVersion: v1
data:
  configuration.yaml: |
    advanced:
      homeassistant_discovery_topic: homeassistant
      homeassistant_status_topic: homeassistant/status
      last_seen: ISO_8601
      log_level: info
      log_output:
      - console
      network_key: [ 1, 3, 5, 7, 9, 11, 13, 15, 0, 2, 4, 6, 8, 10, 12, 13 ]
    experimental:
      new_api: true
    frontend:
      port: 8080
      url: https://zigbee2mqtt.iot.herrington.services
    homeassistant: true
    serial:
      port: tcp://zigbee1.iot.herrington.services:6638
    mqtt:
      base_topic: zigbee2mqtt
      include_device_information: true
      server: mqtt://mosquitto.mqtt.svc.cluster.local:1883
    permit_join: true
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: zigbee2mqtt
    app.kubernetes.io/name: zigbee2mqtt
  name: zigbee2mqtt-settings
  namespace: zigbee2mqtt
