apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zigbee2mqtt

resources:
  - namespace.yaml
  - configmap-settings.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml