apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zigbee2mqtt
  namespace: zigbee2mqtt
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: freenas-iscsi-csi
  resources:
    requests:
      storage: 500Mi
