apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: piracy

resources:
  - namespace.yaml

helmCharts:
  - name: app-template
    releaseName: tvapp-m3u
    namespace: tvapp-m3u
    version: 3.3.2
    repo: https://bjw-s-labs.github.io/helm-charts
    valuesFile: values.yaml
