apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: moodist

resources:
  - namespace.yaml

helmCharts:
  - name: app-template
    releaseName: moodist
    namespace: moodist
    version: 3.3.2
    repo: https://bjw-s-labs.github.io/helm-charts
    valuesFile: values.yaml
