apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flakeradar

resources:
  - namespace.yaml
  - postgres.yaml
  - sealed-flakeradar-secrets.yaml

helmCharts:
  - name: app-template
    releaseName: flakeradar
    namespace: flakeradar
    version: 4.6.2
    repo: https://bjw-s-labs.github.io/helm-charts
    valuesFile: values.yaml
