apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: flakeradar-secrets
  namespace: flakeradar
spec:
  encryptedData:
    FLAKERADAR_API_TOKEN: AgBNEIIRwT4QMKAYVFep+6cCJyvrPcyhd5aFFfocDeobX5kuFgN69w0MPwspjJzh7g1usaY9d9BnMEphjHTfxBhEDgAlSnL77sF0VYv8qlkGytvqHDvZ2y9aFNV3DChp30X6fdElXmM4CRuLm9R67A0qRmYKiGxJuHJ3B8dsSKsJrd2UnT3tglu7U61xtG7V2/n9xR8a2/jWIYhMuh19F6ZUnYkcZzQ0ff+s08IMHdu1pOts+CLDNiXAWe2rpDE85Th9Sa95HMMZij4/CPibRpvsqM79WBDydTm7hyW+V0SZLJ35gTuJNpIznVkQE20GTx++tO3s1f6VhAtrCds5GUbldSSRkCNczbHhFwJ9R9FZoasKCeIaWrf7XGFgPvO/kDwOURuBSodeyP6l8W8yAAaZBqsOTTAeRrLEtZJhe910+VeP8o5wq+qaHx82fNKtO+fcdd2ivJdMndvy7HY6sHt2G4fFlkengtmRAz/TIgS2mZWpaSwlyx3qwoztikDSyJdF6dCyYxkRhAkeViJDJgChrernMyfF5I8kX5YQgp4aAVXWET7HMsTpmw0TO1C8w7wk0vj8tseuFWrAeiHfGpwrGEpO/KcUSUj0X/s7byJPB7QIDeGxtNHZy2jCmJEc2fiazqW20EY4l//pOz+1LH5AHCVeKECtw5MCKM0KUVMjUO/C1p06gB47SvFYBSCgk4LJwKUVm9RIe78yJTMDej3OkgQwxwZrtFs=
  template:
    metadata:
      creationTimestamp: null
      name: flakeradar-secrets
      namespace: flakeradar
    type: Opaque

