---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hindsight-secret
  namespace: hindsight
spec:
  encryptedData:
    HINDSIGHT_API_LLM_API_KEY: AgCObW4QGBYIlgOI3bGVXLUsoJFmqnF/qGY+vf8VLNdzCDUg21nDalsyllNgsjZnSuIx8ZOhxTR064SAbLUj886ZM0uySczpLx2dplLkjDkDk/E0EGe2LvKvvXE/YMbEpQo7VSLYxMQ/EEy6enQuqB2b4s7GgC98YeghYFcxgjYy9LjUVBeAKtcuE+yqEwtSox83YtdNV8K6CfY1CckW4NxzQrjBACYdhMmm8ZA19UIoSodSrW4yVAHcX2a6FwfYEq3vefjbL3Aa+5TfAR1NCYqeCNFpfe3ZSU0zAHDjb33e/xXotuwJxcZt8DkXqXByslqlNnHNP4gY/TC3OoVU0ksRqA/NfBYSVJA67PYW2KEzV16On2DA7iHYXBThIJVXJjQ6Z//27NjVHCptTjMphMRJKVlV77T9qxSOLM0WRyR9ySgL/LfDLrCkxR6lixd9JYInWhxEWqwJ38cdTRsj1TCtvEGRwrkxvxzl7eF9hS8XWVUP5evTH/YZs5eIiNJTwkpfa8tFhFiBF6qsy829XcTHlJwJBh3me4NCm6FZJnPb+axBizma2f/RfZWPUTlXbAIUmjHYZ+9apOrzsr30Dhjbqo3oiJxMOKkUeMLzfctkkFtK9OxqjzuIIGVE/YJxtD5axu90Todjwh0IMd7JLdM7WCRvckyKkrQGL77fEfkbs4SAIh3g33yVOOFJF/D+1iquFv12NbZLykMgnFlZLwbsH+yDno10EggvO3lfkcb6zw==
    postgres-password: AgAgRA+GhH5qMG4f80OKAzsedv2ZhZvV+JGo8LXpoaSDfLB4Io534m+WFCDzIhR0Esc8NPFmWZ5Q2i34JxRGyYTX4aaZ3E3O8WqDuORbVS2W61vraKTtoEZkXU6y6iimBCVbwAtDpQl4ngtNqWNRd9dnqAGAMsSk0CgUAAyBYMycXWlZIuodmbCNpHdXwqW96q4nNJ+1EMdl+tP728t42lWr+16ncfScyKWT8bVcBkF1dBetHyJQfgzcOtHH6ruErzuSKkH8dP7I7bwQjlS2LZx1Csojaz4k9900tKbiYTTGY2epB2JY+dwzPm68TdC11bcNyJUsQbfaUIRr8P6vkNrB06+Jf3eLlpgHrX3EbKnRanY3pEVmQ/hBnSPDykNRJKita0Ftibyt5+piYfXJ6OtvDZblxDtDl6V2TL7EHa/XBtcl4f0ZYXRx3Ifv12pqmDrWGEkaJvO14B6DsvJ8ZNUIv5peoDcSAgZFQK7HCKwbg625bstlb+ztarkWgrJAX58vaKHypwpcFVcE46dlVOvGIhApPhlIAqzrhpeH402uCai8JRya5fdkKKnedQNssO7oRjvmp5vUt3JqP7/wHzndJTdOUTr7Rd20KEzTNinZxI0xuvFiEFSOL8jGVNb5LTC5RV5LrS/Mfz4cZQMwZEz5YJ8+dW48yjuvfb08j6ER18gpsdRoxN5jirJ49BdUAK6sE0tIXjU2JD09O7dzZAvnJrQDUzLpw99Y+5tW/cjuEWAlwRdksg4mxnSwPIXeD7k6PrrK4aC1SbgoSHWK171W
  template:
    metadata:
      name: hindsight-secret
      namespace: hindsight
    type: Opaque
