apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: zero-ssl-eabsecret
  namespace: cert-manager
spec:
  encryptedData:
    secret: AgASq0UUWvlFUCKbMr0hA+7429c9eLU/7PAebFK1k3gM+er7yVLzKJH+TmPYVlqpVD5WMjR0wuixhj3MnpvAOWFsyNXUxk7l/SinKK9yQGbokQ2oRyHx634IrOKvXVN4CHSCocwNYtB9vOokNu+xmJ23IbowX3gjwU9NgXn8jf2LNF2Ntu/h8tGNHzgwAtblDjbI0VqcPVcgfgki+OX1fsI9XOf8fWnL6O6AiOn7eY1MtlQnlrgk2CqkGXWbmarW1JiWNIN0KllLIk+Czl0JLHRkQrxZWfTZj6uEVjZTSPDFGu5tyrGG6maQuX2epKfLbpkegCIjoZ4p4GrcSNZF21qpZuDDcUQFh9vlYJ4iP53cUt7UrFpRjG6pSgb0U58P4LlZE/FzVcWBO5HkaGDvPfwZu5//luy8TIWg5h3LW3ILm+pHxvTQW8AqMY7y9hRBCeM6pUS86LiLslCyEwfMIBl0rVDQae6Deo7GvWArCvgwxCpt0WY/cYjQvTjfy3CVxhs8YMO2v3+Qk3cXA3tGNIQ+FevzseHDVyMUg4bBuHXv/3ZYq8Uc0J/7JvEoemFEevJ+5bkNQBVNEvthlgLoTEEz6dRpj246fgFgLDc7dhtK/JV6k3Xs0peU/m0GUMao4NzpI+FBq1e6LnrG7ypvf1V8+hOgoZIWfp76q20e510yOl09/w9rgbkLMm1MALVLQ8z8Ctie51mzPtSaq17BYTjJZQ/0yuzXPdX/DP8m8ZO+p0gb4xpmWe8J+sI8uHdm59u/2B0Ub3yqUVZs7fMb5WOSnI5x1trlog9o0nz69z7Y/J6AK0aLRA==
  template:
    metadata:
      creationTimestamp: null
      name: zero-ssl-eabsecret
      namespace: cert-manager

