---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ersatztv-config-pvc
spec:
  storageClassName: freenas-iscsi-ssd-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
