apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: freellm-secrets
  namespace: freellm
spec:
  encryptedData:
    ENCRYPTION_KEY: AgC49Em/Gm9W1iVPxb/bl7rwWBnFFnsPM/syR0oW+DwfsyJn5OGQ7eNgCy3/tnnesCjcCDG1nqHrtwnDOiZd73nxQPrWsBtk2w3VOziL7f9v8NBR4NAuI8gYNlfirquCA9PRdLM1LiZUUMi1vUhumats7ujWDl0aqRxW9P5CXcCgNIHkpWGPhukXT1SzUR4um3xq+eKViy3hKV7UCFEKU6o6K0whM16xQFjc1QcPphPIq8/YFOOIPZ+VCVNi1iWZ/u4P3PY2tBmUzqeLkPdFLcLlXbRgphwTrIHICZXl1tbHGjTS2vH+JweHEYIlJLcJafpJE2uZcnkpo8cSPQqBt0CaV5uQzZXZPxxDVyLBB0p9Q0oyS1M9rf9bqL2My6m67AU6fsY86GlcZPQtdxr/2RIDnNBybAbFXfQoRWc5KPDS4llIEIA7NdAvzaT3ILOu8+XLnNFM0DCV8Yqs29ih0xWr+8MZxAMMhg/l2btp4N1k/LX5R/PaUb9LEsm7gdVPD7D1JVV45g7Lc28WnSvSTc1SU5QmSH2sZV2baKK4AW48SGe9wotEqZoB9sCwGqZ98xbg0/SPw3rTAXhutl0ffRhXEOCIt7lnvLf1lfkC2yzw0fmDrdebGjDRp44brIGiMBJvGNMyLpl4jn+t2AWY+bE7JEfQZIHBob2knf/gm6Bk60ie0OLpPXOeJeasPlMCFiFVXOdWkZIyd2qyWb1pLKe8yl7uD3bWD+Wyud4uQrz2TUmMUs+zTxY3Wy06k07A6sSSNTTxC0TNRyzWOaHH7WE8
  template:
    metadata:
      creationTimestamp: null
      name: freellm-secrets
      namespace: freellm
    type: Opaque

