apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-config
  namespace: piracy
  labels:
    app.kubernetes.io/instance: lidarr
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: lidarr
    app.kubernetes.io/version: v1.0.0.2255
    helm.sh/chart: lidarr-14.2.2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: freenas-iscsi-ssd-csi
  resources:
    requests:
      storage: 1Gi
