apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns

resources:
  - namespace.yaml
  - sealed-secret-pihole-creds.yaml
  - service-account.yaml
  - cluster-role.yaml
  - cluster-role-binding.yaml
  - deployment.yaml
  - service.yaml
