apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-password
  namespace: external-dns
spec:
  encryptedData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: AgAxFOMP0UxrKtHBK8RB+gcHHPdY7/owXsryng7gRLApFk4DfptJ+/aX42oroFQymWjCNR3SJzkbA2IqDmE+hhq4/E8ZECZvYNGNc0S30ioKrLeGGClTjru4BJ8NH4QckSXr3Uq/kmW/wu55Knjbp9DEnmOeIDbNanj1s1sYZ/nQzyjvIRxvKniPbNb0XDuZYE6WPAAzw7l1PB5yn1bkc386jtyUDDWO3/Qn6cNMq+CjtguETvlopMbw9gcceH9e3MCaCnU4gIJFXOTEuM0MuqV1JD+u13RtYpCJXxK2a4O1scDHtiG87qLvHkIvi+MvMBzu1NqfxMvSz+UBYwRFgNf5xVCM+82f678EKKD7+IoWZyRsrEKUwArIevbC0LJt5ukEHDr2I4mH+HZtLcQJVSZ/VGAx7bmzl3+GDYJDyBC2IGSlm/VJk41vU0U0IiQeNpIR5K1w/7AAi0d40ivfCQwVv1DzFIsKffJimozqL6of0GxD7gosjL2lEXxpWNqSfAL/t6ohv1/px7TIrSg2DhvCpTDe2vjNKf2E6KobgK6BSuiqyJNWoHkrE9Cn+/1RTjqkEmpWQg7qUbkm0RFg9gGEXP+XelcPjSNbafM7CfE1vy61CK2vGzTVRrbeHiB0iwXc7Sp1GEdztPpTschXQmx2wpp9HzTfSzD4Az+Wi4WVTjNUL+e0BVh3GIWbr7zmMnRiy/NdT16mNSV+
  template:
    metadata:
      creationTimestamp: null
      name: pihole-password
      namespace: external-dns

