provider: pihole
domainFilters:
  - nauvoo.herrington.services
  - herrington.services
txtOwnerId: nauvoo
# Pihole only supports A/CNAME records so there is no mechanism to track ownership.
# You don't need to set this flag, but if you leave it unset, you will receive warning
# logs when ExternalDNS attempts to create TXT records.
registry: noop
extraArgs:
  # Pi-hole v6 server
  pihole-server: http://1.pihole.herrington.services
extraEnvVarsSecret: pihole-password
