apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: registry-cache

resources:
  - namespace.yaml
  - storage-dockerhub.yaml
  - registry-dockerhub.yaml
  - storage-ghcr.yaml
  - registry-ghcr.yaml
  - storage-local.yaml
  - registry-local.yaml
  - storage-mcr.yaml
  - registry-mcr.yaml
  - registry-wipe-rbac.yaml
  - registry-wipe.yaml
  - registry-dockerhub-wipe.yaml
  - registry-ghcr-wipe.yaml
  - registry-mcr-wipe.yaml
  - registry-local-wipe.yaml
