apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: registry-cache

resources:
  - namespace.yaml
  - storage-dockerhub.yaml
  - registry-dockerhub.yaml
  - storage-ghcr.yaml
  - registry-ghcr.yaml
  - storage-local.yaml
  - registry-local.yaml
  - registry-gc-rbac.yaml
  - registry-gc.yaml
  - registry-local-gc.yaml
  - registry-dockerhub-gc.yaml
  - registry-ghcr-gc.yaml
  - storage-mcr.yaml
  - registry-mcr.yaml
  - registry-mcr-gc.yaml
