---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: esphome
spec:
  storageClassName: freenas-iscsi-ssd-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
