apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: esphome-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: esphome
  target:
    name: esphome-secrets
    template:
      engineVersion: v2
      templateFrom:
        - target: Data
          configMap:
            name: esphome-secrets-tmpl
            items:
              - key: secrets.yaml
                templateAs: Values
  data:
    - secretKey: iot_wifi_password
      remoteRef:
        key: esphome-wifi
        property: iot_wifi_password
    - secretKey: main_wifi_password
      remoteRef:
        key: esphome-wifi
        property: main_wifi_password
