apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: actions-runner

resources:
  - namespace.yaml
  - sealed-actions-runner.yaml

helmCharts:
  - name: app-template
    releaseName: actions-runner
    namespace: actions-runner
    version: 3.3.2
    repo: ttps://bjw-s-labs.github.io/helm-charts
    valuesFile: values.yaml
