## Install Prometheus Operator CRDs
##
crds:
  enabled: true

## Deploy a Prometheus instance
##
prometheus:
  enabled: true

  ## Toggle prometheus into agent mode
  ## Note many of features described below (e.g. rules, query, alerting, remote read, thanos) will not work in agent mode.
  ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/designs/prometheus-agent.md
  ##
  agentMode: true
alertmanager:
  enabled: false
grafana:
  enabled: false

remote_write:
  - url: https://oo.herrington.services/api/default/prometheus/api/v1/write
    basic_auth:
      username: andrew.the.techie@gmail.com
      password: PHczpOL72nk7Q8aj
