apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus

resources:
  - namespace.yaml
  - sealedsecret-credentials.yaml

helmCharts:
  - name: kube-prometheus-stack
    releaseName: prometheus
    namespace: prometheus
    version: 51.3.0
    repo: https://prometheus-community.github.io/helm-charts
    valuesFile: helm-values.yaml
    includeCRDs: true
