apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

helmCharts:
  - name: node-problem-detector
    releaseName: node-problem-detector
    namespace: kube-system
    version: 2.3.10
    includeCRDs: true
    repo: https://charts.deliveryhero.io/
    valuesInline:
      image:
        tag: v0.8.14