---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: litellm-secrets
  namespace: litellm
spec:
  encryptedData:
    LITELLM_SALT_KEY: AgAsxQFZ9aQzxxaa+CvBaRT3fgJs/yzejgXw9Lm5Y74PNLWml9pCxCJndVEcCjZrobkoPt3Zg/BK4+R4RmYH30f137Q/1AU6tZEpZJIQSDo6uB1v+7HYpI+KMyasTJgciX+pBmCbfArWbYezNAcQZIkEMdLL7klkxAssnTF6FTU0p2zpbo5A7EXBnF2zYg5Fi0ULAzLeb5aUzHCIdSTXLlqWe6IeaMhWy3615ryuDbhyXHpl1vnvY9xQcYnwBvy5yjnpFZkulYjR0UjjUKt1VOXNWM7swIq9nQWy7k3d0IFh+cS4jUbbkc5bXSFUtSKupKgQEg1T8QGA8RnEpqn77xfRAPeCx2aKFz2lxTsjSyMjLXzn/3EOsnSifRbxVd2l8O4jEcdEILzXP9Rcz+Yryn1ajTCFbs+VflJJmbmnczT+T1QpGDrZVGaDMFE/p3EWdr12WhtwCUmAuNQKdazam1JOfvIV2PvAIZshSoBnoNrVCWpERYJXMiuDNJsAxLuazhFGad6Q2dlJ4AY+AfTD4gCvtqL9YddyLwv66u+lACX0uPMStCZPd43NOPCx50iphACWLw5zNIy6EykMT7yOHwqUOwlnRd5IKFUH++r95gTRl/R5INnuSZkIJmG2QSXBI6mpHcYiDxmgQGFdyfB71JKmpOxeD80t6T8kX083joD1MPe5aPLZMGqr4ryvlCilerQatlI4GMpjGubR8UO1W8OTLbic0B/BmuXPvq0ifacQt2xZhHdW4/e9vG/jMeTN9iUn/PM=
    masterkey: AgDVH0+RNzr9YDPtvBPVszHIbRaFyx6OxmLG0kl5Ep8m/d6uMOx/Z4hXy7o4FPm8kpJY7H/eTpkLPjv52sTXPohLNE1QAaFzmqz6uMwPniYSafyzWCVXryPfgpiv5WAfRLT1eayaaCZM+8dopHHzEjs/7uaAlpMW83SimCCqlqTx3IO/m109RSaCddAqECF9rzweWTbDPApsx2l3tu+QktEG2AxFpUG8r1UMRTWSpO4bn6Z6yPq5+5qpjV5Xz9LUVMrSzxbPaHaLCFlC4f8r8MFEZHeeidokrHCEWC35FHNFMrVBZkJwJozBx+0DK4crOKhT2B34gpGV4i4HbAeO5fwMbDXI4KDkyAZKuY9v0TUZbOpmBgGW3dtKNV7r3nmp0icf6iZNbIxQvJn3CMR5xBHkes1YzxRe3VW4xM419GSAoYyrLEsJC1JGVfMvk7ePg3qkNNk7rFez2ZAJt3fS8Dqcms0dpaqfOHGutYOlGEql4rs0hN3ht2QDxjnbuFtSeoMzdOQvp9WJvsGl9zaAwNGkSrl77Yj5JlwJ8eZ0Jfc/yJkUFlMTtOU2J7mCq5bT35s2Nz/HWRBOclCVi1Eu/bOPFlLBc2R5wqhrsGb5Udcy7PeY7TRqJELMuSp3SmVZONS+3sYSpm8RiexyDvkM1IDZz4wz/TcbH6M/0y/OKRcIzBgBOuAPzko2/ojPVoQ+d4IimYgDbTl6Dim6QnvJHtwDPjO7lBj1q543wLg5mB1rn8BEboPQE/ZK86qQFTfJqYoJxpU=
  template:
    metadata:
      creationTimestamp: null
      name: litellm-secrets
      namespace: litellm
    type: Opaque

