apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hasseso-store
rules:
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - authorization.k8s.io
    resources:
      - selfsubjectrulesreviews
    verbs:
      - create
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hasseso-store
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hasseso-store
subjects:
  - kind: ServiceAccount
    name: hasseso-store
roleRef:
  kind: Role
  name: hasseso-store
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: hass
spec:
  provider:
    kubernetes:
      remoteNamespace: hass
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: hasseso-store
