apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hass-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: hass
  target:
    name: hass-secrets
    template:
      engineVersion: v2
      templateFrom:
        - target: Data
          configMap:
            name: hass-secrets-tmpl
            items:
              - key: secrets.yaml
                templateAs: Values
  data:
    - secretKey: db_username
      remoteRef:
        key: hass.hass-db.credentials.postgresql.acid.zalan.do
        property: username
    - secretKey: db_password
      remoteRef:
        key: hass.hass-db.credentials.postgresql.acid.zalan.do
        property: password
    - secretKey: sp_dc
      remoteRef:
        key: spotcast-secrets
        property: sp_dc
    - secretKey: sp_key
      remoteRef:
        key: spotcast-secrets
        property: sp_key
    - secretKey: alarm_code
      remoteRef:
        key: alarm-code
        property: alarm_code
