controllers:
  autoinstaller-generator:
    strategy: RollingUpdate
    containers:
      dhcp:
        image:
          repository: ghcr.io/andrewthetechie/home-k8s-pub/ubu_autoinstall_generator
          tag: de7ceb7f1edf56c251d27fc8cd69b0605e8cb604
          pullPolicy: IfNotPresent
        env:
          SERVICE_ACCOUNT_JSON: "/config/service_account.json"
          BOOTSTRAP_URL: "https://bootstrap.herrington.services/bootstrap"
          BUCKET: "bootstrap-resources"
          ACCESS_KEY:
            valueFrom:
              secretKeyRef:
                name: autoinstaller-secrets
                key: ACCESS_KEY
          SECRET_KEY:
            valueFrom:
              secretKeyRef:
                name: autoinstaller-secrets
                key: SECRET_KEY
        resources:
          requests:
            memory: 64Mi
persistence:
  config:
    type: secret
    name: autoinstaller-secrets
    globalMounts:
      - path: /config
