apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: otel

resources:
  - namespace.yaml

helmCharts:
  - name: opentelemetry-operator
    releaseName: opentelemetry-operator
    namespace: otel
    version: 0.39.1
    repo: https://open-telemetry.github.io/opentelemetry-helm-charts
    includeCRDs: true
