apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

helmCharts:
  - name: kube-state-metrics
    releaseName: kube-state-metrics
    namespace: kube-system
    version: 5.13.0
    includeCRDs: true
    repo: https://prometheus-community.github.io/helm-charts
    valuesInline:
      service:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: metrics.nauvoo.herrington.services
      rbac:
        extraRules:
          - apiGroups: ["argoproj.io", "cilium.io", "acid.zalan.do", "externaldns.nginx.org", "cert-manager.io", "bitnami.com", "k8s.nginx.org"]
            resources: ["*"]
            verbs: ["list", "watch"]
      customResourceState:
        enabled: true
        