apiVersion: apps/v1
kind: Deployment
metadata:
  name: hass-home-assistant
spec:
  template:
    spec:
      containers:
        - name: hass-home-assistant
          env:
            - name: spotcast_sp_dc
              valueFrom:
                secretKeyRef:
                  name: spotcast-secrets
                  key: sp_dc
            - name: spotcast_sp_key
              valueFrom:
                secretKeyRef:
                  name: spotcast-secrets
                  key: sp_key
