apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: hindsight-secret
  namespace: hindsight
spec:
  encryptedData:
    HINDSIGHT_API_LLM_API_KEY: AgA33sxCZrIv5M3VxNk6VH/tFgb2Ar8Eyy4Hmfi7utuHmpoDV3+qykoPRTXgIWPV3zLss4Z64sI7kOmYgz7jueMVqmJEskYnfbHNk0KqvVo/Yk56ZNYu7p06nAuhYY8lPW+q7lGv3R72uGKWPnBoUyshL7MnID5y1X1RZhbxEEm0lhbDQjOqbXHPZ8O9PZTP85ttcbKYPNat8IrAYujOQ5rv6DOKhfsfaZ5k+ta/MHvo6Bn9LKS9+D7LlEhZRhAYrf5ODL4pP+2+iTxHMenm4b1Cwr8Of9bQwCl1fza6DEq07KNwpkDokiKmdX1UGLKk+qYXRNHdlhT4Vdfo8LWMBHZ9l/IjiAvDqIQM2LsSGgCCyk4eSc8IbmRvCOqSqczt38ErA2bYx4aKkvipzGHbhV8WXAA0BmrzYQtGtzzEUdcniNrS4zAiuNpz0X6LlJ3BFLYjYkp1dlvZdbBvoQ364GxxmvMGfB4AlVMo/pe4mDClg6fyq0tdiikzp5GW1d5e+1jRFgcg3lRpUc1iQe0XdFwl08B5iS+neqHiLRFLLyQzVua2kYX884g7D7dBftEGHyPeDSQcGuY1Rt6ZejaWTwTwk1GSG7tiNi6gPjoTJrUZfEukKv6oVHGuA/IXBSvbTu5Lcmz2huXo6REi1rO8eNq24fiqM6B5KQEuV5lfavIxJ+EW3IjeeXUv2YLISOoPMW9v37K+NRRqevwivqy7021DpAGWEbeDooX3KOouZUWGqr0EwV3MpzUISSE3Bc1Q9aYvd/erTVYfxg==
    postgres-password: AgCSOl0dYCzJKE8BYpey5Wy2vTopE6Q++bw452RMjaAgAueU/6QRkdL8HkX0dhjsmDzHTtECrmvFAa7scfdwHwBa8iZKPEAF3PVqb0dMadgaOlICcoC1VNIIXYI9PvbSc0dxxfHn01ATHjyG7nMDZsTNrnd2C8tiPW9vckahqCuLrMcaNL1U2oZNTOEnYJviwFOk6d/q5RKJEVOccoxo1TfTWoe0fQeQpZPER1OfX3iOXr7vEY4+hjb68itB/zEn1NpYpMIeQvjOGtKqXWc2F0ouRpCB/hDGEG3uohMN1aDxQ4x/pwra4OH+zCBRaJV5BOr+pHu1umWSboiEAPfBJkhVpQs3hkPpT9pHALXTfW7hEI6cZb+xyog5dfAsEuG5yE3Fx++Fvr8fW8IWNNTOfwngRlO1FUrpnBGoMcCFCQmuI+AQrcIKspNLYrVxMFXI9Ftfrq8WVh76vTWEeCZ7OkJoAz65tSVRZemcyKBR+UmfGwOZcHQ78CnMmXR8p//oB/tX8+FxXI6HzkEfLIxgj2GzjWet9U+t/cvP8WsNnZnd3DyqgQCN9d+0alBu+MaMY1B5IKizLZIYXy7azDJC3RnfrmoeXv4ysYnVgyDgG4W+3QE6dOSdAOH1NIzlsNCFCPPudiM5K/ca5NLW4sy+gKhyf24VTr4wq8u/hQWkKggGB29tR5qPQX7hwfdUV+xSnrSOBDY6Etg2Z4A01bEnuLwuP9dJU0z92IU1KlvvcSEuy92Z6Er4rk8BLGTgEri3/O5u+ExmER0uZlgW9Sj28kKl
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: hindsight-secret
      namespace: hindsight
    type: Opaque

