apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stirling-pdf

resources:
  - namespace.yaml

helmCharts:
  - name: app-template
    releaseName: stirling-pdf
    namespace: stirling-pdf
    version: 3.3.2
    repo: https://bjw-s.github.io/helm-charts
    valuesFile: values.yaml
