apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jellyfin

resources:
  - namespace.yaml
  - sealed-jf-credentials.yaml

helmCharts:
  - name: app-template
    releaseName: jf-liked-songs
    namespace: jellyfin
    version: 3.3.2
    repo: https://bjw-s-labs.github.io/helm-charts
    valuesFile: values.yaml
