---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: credentials
  namespace: jellyfin
spec:
  encryptedData:
    accounts.json: AgAhcJfFpoI4rZcaWz+hRoirtHwlDTER8p74PE5trId51jzy/0OxPmq8jIQc1mvcN3MX8EsUX5hzr3JFyhFnrTPWqPRDB6hGtiIAe4TGzw3SyUN5U6yguHmfPq0SJ6TRmf+U2XShZKTaAvCnSP5fYJZvUkcIbVAkxvxoioxYYABJ/0SjZHqPxku7tigmhtmBlPwn1Bm3QxoGamWNAzbZQNMfxarUjtPrQYIJ0+RfUkHovvilaJvKmUqU2MGBjqvBuqz8ei4E2fmQyA0Ozc28Zjwpg0OK9/q8IT1+ZGbh4WcABf3cp441sJVsLbMHchal2HxnVpnED2UYIKACfTQNwjU81kMguKkwq9w24FaWnXmcQR6PK4zczP6f5WcQEgWSk9+xbePusMDIGURPClgagkKj9FLEUju3Q9GaKhXPtob/g1q+OAsXxxdRi7tDJMpwRFlkMkZefVlNtpJm+gi/GjhzYStV2bE55rp8ApaWGPj8GJPHMATjxhn/rz9xDB1g0sVE3/qixAU6TVJ30/RcdfcZYsiyPcSC4Emin19a1qsYWSo0nQPHK1GrQ3xOOypDKtSLpgMMsHKeWApyEWx1ZH/jiUULiyY+vTeI/l8Li0q+rzCA1RnyE/9QldXRTP0FTQ6nLKJR9KsiZl9eIJV3kAsKM1osrl9I/y65Wjz4dDiyyFsjVTOgNn+dbZXskWNlP4VPdxoCNtX0oHEFhay7YHqlmOnVKUXmBqcHezhbC38kA6eN4QQdGeAXI8cjI/N9UtycuEPXyqter4PQne7W0ZzkqZVIHQX6upNsv0u+oueaEacHg5vjGG4Szx01t4yvxMui/qjJh1/ad+kp5Mo5tm3zqDUfnEP+s7CbEqYdzgWx0qKkwudyrrjuC1j4
  template:
    metadata:
      creationTimestamp: null
      name: credentials
      namespace: jellyfin
