apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: emulatorjs

resources:
  - namespace.yaml

helmCharts:
  - name: app-template
    releaseName: emulatorjs
    namespace: emulatorjs
    version: 3.3.2
    repo: https://bjw-s.github.io/helm-charts
    valuesFile: values.yaml

patches:
  - target:
      kind: Deployment
      name: emulatorjs
    patch: |-
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: roms
          nfs:
            server: chrisjen.herrington.services
            path: /mnt/data_pool/Roms
  - target:
      kind: Deployment
      name: emulatorjs
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          mountPath: /roms
          name: roms