apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubelet-serving-cert-approver

resources:
  - namespace.yaml
  - service-account.yaml
  - cluster-roles.yaml
  - role-bindings.yaml
  - deployment.yaml
  - service.yaml
