apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dhcp-reservations

resources:
  - namespace.yaml
  - sealed-password.yaml

helmCharts:
  - name: app-template
    releaseName: dhcp-reservations
    namespace: dhcp-reservations
    version: 3.3.2
    repo: ttps://bjw-s-labs.github.io/helm-charts
    valuesFile: values.yaml
