---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pb-pvc
  namespace: pastebin
spec:
  storageClassName: freenas-iscsi-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
