---
apiVersion: v1
kind: Service
metadata:
  name: pastebin-http
  namespace: pastebin
  labels:
    app: pastebin
spec:
  ports:
    - name: pastebin-http
      port: 80
      targetPort: 8080
  selector:
    app: pastebin