apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: scanservjs

resources:
  - namespace.yaml

helmCharts:
  - name: scanservjs
    releaseName: scanservjs
    namespace: scanservjs
    version: 0.9.2
    repo: https://charts.gabe565.com
    valuesFile: values.yaml
      
