image:
  tag: release-v3.0.3

env:
  AIRSCAN_DEVICES: |
    "Scanner" = "http://10.0.0.245/eSCL"

persistence:
  config:
    enabled: true
    mountPath: /app/config
    accessMode: ReadWriteOnce
    size: 512Mi
  data:
    enabled: true
    retain: true
    mountPath: /app/data/output
    accessMode: ReadWriteOnce
    size: 10Gi

ingress:
  main:
    className: nginx
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
      gethomepage.dev/description: Scan from the browser
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: Misc
      gethomepage.dev/icon: mdi-scanner
      gethomepage.dev/name: Scanserv
      uptimekuma.io/monitor: "true"
      uptimekuma.io/name: "Scanserv"
      uptimekuma.io/type: "http"
      uptimekuma.io/interval: "120"
      nginx.ingress.kubernetes.io/proxy-body-size: 256m
      nginx.ingress.kubernetes.io/proxy-send-timeout: "3000"
    hosts:
      - host: scan.herrington.services
        paths:
          - path: /
            service:
              identifier: scanservjs
              port: "8080"
    tls:
      - secretName: scanserv
        hosts:
          - scan.herrington.services
