apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cleanuparr

resources:
  - namespace.yaml

helmCharts:
  - name: app-template
    releaseName: cleanuparr
    namespace: cleanuparr
    version: 4.6.2
    repo: https://bjw-s-labs.github.io/helm-charts
    valuesFile: values.yaml
