apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: it-tools

resources:
  - namespace.yaml

helmCharts:
  - name: app-template
    releaseName: it-tools
    namespace: it-tools
    version: 3.3.2
    repo: https://bjw-s.github.io/helm-charts
    valuesFile: values.yaml
