---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseer
  namespace: jellyfin
  labels:
    app.kubernetes.io/name: jellyseer
    app.kubernetes.io/instance: jellyseer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jellyseer
      app.kubernetes.io/instance: jellyseer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jellyseer
        app.kubernetes.io/instance: jellyseer
    spec:
      securityContext: {}
      containers:
        - name: jellyseer
          securityContext: {}
          image: "fallenbagel/jellyseerr:2.1.0"
          imagePullPolicy: Always
          env:
            - name: TZ
              value: "America/Chicago"
          ports:
            - name: http
              containerPort: 5055
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 30
          volumeMounts:
            - name: config
              mountPath: /app/config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: jellyseer
