---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyseer
  namespace: jellyfin
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    gethomepage.dev/description: Request Movies or TV Shows
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Media
    gethomepage.dev/icon: https://png.pngtree.com/png-clipart/20210128/ourmid/pngtree-pirate-flag-black-png-image_2824280.jpg
    gethomepage.dev/name: Jellyseer
    gethomepage.dev/weight: "2"
    uptimekuma.io/monitor: "true"
    uptimekuma.io/name: "Jellyseer"
    uptimekuma.io/type: "http"
    uptimekuma.io/interval: "120"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - request.herrington.services
      secretName: jellyseer-tls-cert
  rules:
    - host: request.herrington.services
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jellyseer
                port:
                  number: 5055