---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kms
  namespace: kms
  labels:
    app: kms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kms
  template:
    metadata:
      labels:
        app: kms
    spec:
      containers:
        - image: p3terx/kms:latest
          name: kms
          ports:
            - name: kms
              containerPort: 1688
              protocol: TCP
