---
apiVersion: v1
kind: Service
metadata:
  name: kms
  namespace: kms
  labels:
    app: kms
  annotations:
    external-dns.alpha.kubernetes.io/hostname: kms.herrington.services
    uptimekuma.io/monitor: "true"
    uptimekuma.io/name: "KMS"
    uptimekuma.io/type: "port"
    uptimekuma.io/interval: "120"
    uptimekuma.io/hostname: kms.herrington.services
    uptimekuma.io/port: "1688"
spec:
  ports:
    - port: 1688
      targetPort: kms
      protocol: TCP
      name: kms
  selector:
    app: kms
  type: LoadBalancer
