apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
  name: 01-bgp-peering-policy
spec: # CiliumBGPPeeringPolicySpec
  nodeSelector:
    matchExpressions:
      # match all nodes
      - { key: somekey, operator: NotIn, values: ["never-used-value"] }
  virtualRouters: # []CiliumBGPVirtualRouter
    - localASN: 64513
      serviceSelector:
        matchExpressions:
          # automatically announce all service loadbalancers
          - { key: somekey, operator: NotIn, values: ["never-used-value"] }
      exportPodCIDR: true
      neighbors: # []CiliumBGPNeighbor
        - peerAddress: "10.10.0.1/32"
          peerASN: 64512
          peerPort: 179
          eBGPMultihopTTL: 10
          connectRetryTimeSeconds: 120
          holdTimeSeconds: 90
          keepAliveTimeSeconds: 30
          gracefulRestart:
            enabled: true
            restartTimeSeconds: 120
