apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nebulasync

resources:
  - namespace.yaml
  - sealed-secret.yaml

helmCharts:
  - name: app-template
    releaseName: nebulasync
    namespace: nebulasync
    version: 4.6.2
    repo: https://bjw-s-labs.github.io/helm-charts
    valuesFile: values.yaml
    kubeVersion: "1.28.1"
