apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nebulasync
  namespace: nebulasync
spec:
  encryptedData:
    PRIMARY: AgCOp8+9JgFC8vVn6ZyY3OJaNCj357daJJad8M/yJllImKbjS5FDmmb0+nfyB100Kflj0qwiBupX/VV2iEmehzwkYesOrQoSTJP8Rh+lMgSdvc1zKgbnFC9ZafOLy50Cg3Y6HDRHZCjWzon1dePvz3iL9MZ9BTHJX0n0hO2rV6pFA1/q+LsX6TviFiwSNTY8uUKS0xvW1aLeY+UsaZh6H4x8Gjk7c8GxzWsougZSGdchgj0t3a429eXOdxkbMtl7VGSqPHO9d65VaLC3F+1g7eiMBtolfeHqnbkrJvjoOa736qn8GGm9syd6Xa/LRSX1wVa6/lP5wIR2QjeHVGVp4jWMoaWn8U3P7IW2S+ht+Z9TSzDmPhQlh+QZFsMoIqb7ypa6r28XfXKgqqaeK8zjc+3EoQnNbxY/QdP5dfij10zvS/+mpXaFdKA8xZ8lHnAUg1SWNC1j9Spxam9krop5tFymPKKuBZWhpqiS+QJfWhIPwpUtmGR9F02U9zJ1MziqJc5ebjWAXSYFc2O2yEcyTXCdUVQxmxnnTx10pbiAtG6ifwWl9bfYgDWnr3GAr/0yrV7XBUnG/BW5I7XGQwbwqWr4MUEgxiLfbS2gEBA4G4jfagsgXYrhtxz6kc3XgwPFTMPjCgSna1q2JWtzu9FXsS4DVUmUQrzN/OPsTELw4NGzeUHdwcqqmBfbyaxC/prVzliDZ8xapa+9G9/AaY6PpBjand1usRCws5j4I5WAtX3A/RA3/BGLR8itq75xKE9ZDw==
    REPLICAS: AgDDQ0yeYR6/xb5qmIAsrqDD0MhWp3L1FiKtUkNv4Vbb/m3Ltzz3gXOR8HxxixuK16frIvw0zRIpp/C4jQhrL5esJuQoXnYJhh0k2CXclts3kCOVFD7qwjW8qdvNnKP+lRsznwVfgqUmVTuz9nzjuTMsVmw5jr3mmXXluXsrPKrjd3qJUNOQhwLWU1iCIaTUvI95aYTOtkek3xtTCdeo6b2dibx6mvFyPfg7UKDaUYPxXPQfmxG93aor+QfeY8RsL8BKc6hKHs4QIZyJTejOZ22FxtuDI+kr3r90T/LhFoY1g0I0J/unSzuJn8w4HjATdex5xPDWrNuOL5EuQPayxxrHIdONG2dAJe+K+WD6kWnK2UgarOiimnPjYNGCvtWXqRbGu9ZGhECCgJ4P/+NcCHcR8rLlNFKyw2Z95j+Sp4Uhh50c9fCo0OHG8c2S+p6GLVLG9GY5983Fr2Xwc7oUvG7x11q9jWt3k6o8U4dhpcRH/if2JBZyCq7pRhMkMB9F+GLGUuAquSv3kQKlKFEapGz0rd8Xhb6JICMY4FVa754Ha1piBfN61Y4hVJUIHBmt1awaYnMhpu6DWQEjltC2jLxtjs01u09ZQKZBwS9MaUDF/4y6qOmt4ZTkaKGsPFdoPUpa0IZYmo1f7aPhBEVeFg3ua34rjsMFs1jlEOYodyhnu6zOMnrZuO3eYZaWhTsINc8VODoto19XPm+VVh5C+ZNZ2420KAUt3WBe7dnsO/mqsygbEiMPOepHDXjCaKeLHA==
  template:
    metadata:
      creationTimestamp: null
      name: nebulasync
      namespace: nebulasync
    type: Opaque

