---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: discount-bandit-database
  namespace: discount-bandit
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: freenas-iscsi-ssd-csi
