apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: discount-bandit-secret
  namespace: discount-bandit
spec:
  encryptedData:
    APP_KEY: AgCjVeCLQAlspBeimWLyjfVYTS2asSk4HlM94CW5oGz4n3vOFl/Dvf5JLreO3+Ck4+lXhHSwMK49VCbGuaxJVn0caULIXZV2m/z/3Mjnx+4YKT0G3cDrk0wCdSSrgcG2HfsmRrjxn57KKc3bO6UxHvDBTSEl0CaCO0rqkG3zs3oz3dWbA6bhMGb5+I2KtvsdkxUKImeeXGMfK94BZkTDCgmUeYc6debwTunI6AWFaxzIDENtNfLiuTWfFKaGB3gQBgrEFTbahAbA2tzcgxpW7pqN/PKyE1yrZsunQV9FD9IpPLC4M+N363bcIh0kmrUiJJ3cmkpK/a7sccFhZwN/AY5DkrdiTC9RhjC2Xt6kMpcrx2m/CsAMWxH9Bj7CyFSAQO6VGYHSrHF6wJde9JIIc40VYQu+QQ7zEdStGsBfzPRCX6+PeoqM3z3jblddsF3a/oLKYJPGoxbEBoxMjLbhJTT/AwcnRihC2i/FKzuPsa+g5mBGPVM1U2k1rMKlaLV1xVQE8Ji8mNvSMHlFnelCvrqDuyDi6a+pydwopdIWqzaxkVrHzn0B12CmWgAqyajzCafr+x4iTyuqLCPNor0NI256/iUxLlfL7mk6kCHkNaUcfl2VNiFZtXSZ/tyVjRPCr2AKoNBJPWHApKz5DNzdNPnCMm7ujHj7DIfSt5qyYsJSgEipVkF8JF33HAegacA3YJgc86I/ztj4rseNP+xq0SID9x+mS1Xl/Ey60bfMKMRMvFhx9QzBJ7rlmX3PrxSR5h9CS/w=
  template:
    metadata:
      creationTimestamp: null
      name: discount-bandit-secret
      namespace: discount-bandit
    type: Opaque

