---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: manifest-auth
  namespace: manifest
spec:
  encryptedData:
    BETTER_AUTH_SECRET: AgAIce618On3zJxnk43K4Z1uOpnAA7sZFlEgD8GeCJuxeP7IRsGQq7MU2m6tNYNHrHF3sm/JObrg+UqP8Us6iOCZkb1MRMJJc19oJ/C3hAQ54jT8OxqefF2pLCxNhHxKn/PIfgeC2uBVwFuMhRunC2prrFOlyn5eYORm6vkIayhHwTSLGGPLUDHyU2YnFExizIT+RCbSm//FBUBRc750Yr2JzT7wDQjkMwr18UGXaKgYt7vXArYiY65sw9GRUK0np1MormZWAj4rB/nTPcx9RiTxEVmJQ+MSy3RUb2I0deyH8dSkl04J4nd6jTdT5UiJakPCEPGeV8OzfaLA/3qu99kb4WpnSW7FlkdeepzheG9J75PwdgKgc4YBuTnV3QxmHJCTUoEEEdB7qmA0Jt5o08xSmIy7R3QOB02+3CMceF83lvJoVfKlnAtcyEVBSKM+zS4ucKAt9nOMp3aAJzRgWC/avq7Du0i6Jq0y7F6h+k/R7KP/fa9ujd8aaZMsACO39UdDYQniWwb1pqecqllOJt2udwyGUF3Er8rAJ7ggvtVVvgLmIQBol1m3rusNLGORwTqIU5m7H3p9iSdQnAp9fwNdRI5IiSgiRTIa0FmucYMINPsutlMOaLvV/TeZn+lt94rdgnuLx+KND2bxl78mOz5Nx9zDDPFrQTtFXQ07ILKvTI+sYAChjQfnjxJbiz/S6bYkOeOatqX2OC69lY3Woo44EIUUf+E5wqcg+L2Pi+mJTZGEki6BXC6sC9nDp+UPMLeCa+aR8mB/5GbtG1h+qcvo
  template:
    metadata:
      name: manifest-auth
      namespace: manifest
