---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: lldap-data
  namespace: lldap
spec:
  storageClassName: freenas-iscsi-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
