apiVersion: apps/v1
kind: Deployment
metadata:
  name: castsponsorskip
  namespace: castsponsorskip
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: castsponsorskip
      app.kubernetes.io/name: castsponsorskip
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: castsponsorskip
        app.kubernetes.io/name: castsponsorskip
    spec:
      automountServiceAccountToken: true
      containers:
        - env:
            - name: TZ
              value: UTC
            - name: CSS_DEVICES
              # kitchen google, bedroom tv, living room roku, living room tv
              value: "10.10.5.10,10.10.5.40,10.10.0.170,10.10.5.41"
          image: ghcr.io/gabe565/castsponsorskip:0.8.0
          imagePullPolicy: IfNotPresent
          name: castsponsorskip
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "100m"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
