- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: media
    nfs:
      server: duarte.herrington.services
      path: /mnt/Media/Music
- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    mountPath: /music
    name: media
