- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: downloads
    nfs:
      server: chrisjen.herrington.services
      path: /mnt/disk_pool/Media/downloaded
- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    mountPath: /home/andrewthetechie/downloads
    name: downloads
