apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: reloader

resources:
  - namespace.yaml

helmCharts:
- name: reloader
  includeCRDs: true
  namespace: reloader
  releaseName: reloader
  version: 1.0.41
  repo: https://stakater.github.io/stakater-charts
  valuesInline:
    reloader:
      reloadOnCreate: true
      readOnlyRootFileSystem: true
      logFormat: json
    deployment:
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: 
            - "ALL"
        seccompProfile:
          type: RuntimeDefault