apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: firecrawl

resources:
  - namespace.yaml
  - postgres.yaml
  - nuq-schema-cm.yaml
  - ingress.yaml

helmCharts:
  - name: firecrawl
    releaseName: firecrawl
    namespace: firecrawl
    version: 0.2.0
    repo: file://./charts/firecrawl-helm
    valuesFile: values.yaml
