---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: git-sync-ssh-key
  namespace: openclaw
spec:
  encryptedData:
    ssh-privatekey: AgCmbmR5QWZLBBu8tnJ0Fn87K2GSf/qD4c8dv7B4tQtG/ZqY1ndQwNm1y8D6u55VTh7wodafU0LFjzPEZZHiMQkZ5TpxHT3U5JhGZDgf7mGQXE7p7bD7MX7pjdsDzGSoyz8Iht5VIuhKySDlr/IX0jdaVxLSpkUq6kQVm+MQZoaWx+jgsQrVr2pyAD3rt8O1wun8VVI7eXUz1E6Ry33lu33+927UURH548vLUAi6yjtSZEZAS/8xhFky2vLgoLN9ZezxWkhGlhzEV+xJhNU+4TzyFOmDZs9l+D2ypTNhTuHh4PbQS8rkw0Z9WakJcrMu5+8NE5EVIooeFu1OgSHMqWUqFz55ZHd4OXj9e/vVi1nT662h+oEz+S9rZW4yQAIwjuOfcItzpGIi2+5Qg3xwFI9FzPR5vyqj+X+fIR9c32X8CjNoP1srzBxQMp3YskHGHPRegzdM5zzuK5Jkg0nZbzg+o+eaEXYDTt1vkpTNnodAShiPLhSgHHKsjAArVB9UsIE1YhjieMT71Wu4zRRPHGKDq5JycJgK7EkZb8D9d7QUbhWoL1cy0kstJCyYyvhOK2C7Y4uSAXS22uQiC5RkeUrHVdZ/f7FQzh/lnBp0x6adYB4Ijb59W5+QCwrlpLBhTA0+R/r+BFyx8hT9pebP0lh2VSPKp3Kp7OhVhE3Newekp8WxJdNGpHRF/uzHkic7lTc8uQBkc+tuhICDasO0CeOmmPARxjLm41hVph4jYfCB81UZOpwhn1PqMk108UoKAmfjuXO+Oy+H8mLeeRBKEZbFIO0t4rnaWY7XzjaLIyDOtutST68ZBQg2E4Fk71DRWX0S6ufY8JudWV4J7STpH/N8APB/aAbMHbPWZU+60BZSxcTxx4qFcUJE3pk9EKPapwSDU9HsBYQDy9rXTk/JyrCGNhXV7V2NX2gT6Zmt9ERNr3EEaylPjvREoUa/v0dWqORJVpxwqk2oRP4cADvm84rDd2RMscf9O3xCSSzhA8o3GZHT9ORQkFCj5SKMhBcRglcOOglURVPzgSqCkfFU6E5GgwbxcCegySvuXxWDWcZGKTHp/jdyJdigZQOhnUCsB3iI9cXBWHIxsqU0rBRpIoY4HDScnG0tXqR0aI4KMHUqXlL4n73e8TSpZZz87aWXMWD8L5kOCpcFCDKIJhXT6lMsFp8j8Jg6XwljYKCdfKqkr3Tp7IlINCDCF4S+zJs/lIvLNM/rWo6Ghzbp5F/jiUq6MuB0f3v+QskeagN2A8MubKkVzbIiBgbtSByNj6V77V5D4ItHVxQqLOmNnas=
  template:
    metadata:
      name: git-sync-ssh-key
      namespace: openclaw
    type: kubernetes.io/ssh-auth
