apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: netalertx

resources:
  - namespace.yaml

helmCharts:
  - name: app-template
    releaseName: netalertx
    namespace: netalertx
    version: 3.3.2
    repo: ttps://bjw-s-labs.github.io/helm-charts
    valuesFile: values.yaml
