---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ha-mcp-secrets
  namespace: ha-mcp
spec:
  encryptedData:
    HOMEASSISTANT_TOKEN: AgBv1tqCjENBEvxBo69DpEwNpOBkrhGtnfoTRTiZxjT17bnLWXfz8uBiZYT2gXKK1iLr60csHKaOSLWaX7j/l7tEw1J/Of1Je8RcB+yuZ0igJMC8fvRnkG+rnIz4de5UQx4FfW1vQmlC/29xPKQtIuyhCPgqtR4E96vl/G/ieKPw/PJtNFSbJ90IsczZdpHbtxJHxUEAMnthPx5Q0u/CZlRkP+3TrXQ9GVTbvf0mN57LDKWrjgwCQ/ys4N0ngznEkvKSizAUqylyHkwB/+5ahI2yeE9Id/F8wtZluDcEo7cTuNwpx9ModXpe4ZMZ5PDdiWfsR+VQpNukvxLbFYV4xfJD2N55S2n6BqDsMzdXH+YEUt7RWfxlgg1CY/HqwY8uYXWLK89iIHCqc0awLwz5qHC1HWARdj1mVdeFR3vKKD4NeUIuHIT3G31H2DrtLcN8urvrRa1WoU+l1/t1bN42TvbLVgyqdFhYtoy0fCL/miQscx0JdrJ86QeyGvf+6Ovpe/feWnt72iBin4eTW/oz1WGUV0vkQwVTAlHbJiw8axi6oXW+n2XZr0gnlhysOFcCrtXKyUA/7mxkz2qbV2gUfZo+sdj/ZM0UAVOp/Y1OK0pVZVhnLtp1Kva+l+DXr4xg8WCpXPnYdBLoDurTmWPXGNSeEC7OtO850x8f2K2jPGUoBclUj7BtIvFVmWbvSqkPGokxjzNr4VPpejreyzIlUV6KQqg19E/Lt+OG7bWCJC85NLLjYP4LwRntR9YGz75H75rfszYtstdjRoiE9NJHiNBOEsRdn17QKKgOo2abl2vP2K7Ev3+iXQ4LNDXRrF+XdPxPZNt+iL5L72mYF9qAWkGMuQfZ8Kc4xkrltOOuBXP23DUaPhhzrEFmKULn5wr/wGqxqOsRVb1mL3X5j2VRuxvPbFl2vyIk9VpnT815wgMDE/8I6KG3vl0=
  template:
    metadata:
      name: ha-mcp-secrets
      namespace: ha-mcp
