---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ha-mcp-secrets
  namespace: ha-mcp
spec:
  encryptedData:
    HOMEASSISTANT_TOKEN: AgCDbWtQXnVLIUMXP035bbfnAr0LBcHFEkCyp3xuWYlA5OqU4QQbkwXw3OO/sHLXhymyAq7fANjoOmblik5/QOcRXZCI5xtl6pM9voKMhfddg8kTTWOdwETcK6yDPwRGZ16X6b8fLpJ1Fvx4DuUY2rK/k28g/cWR4d3Xr6yWNSkYtHSyZ7Jv9FzhxNXRRxlkWFtWq4W9X+eSOGOHUc6iPcYpaqztWPUpAuU09p+2t+R+0/KFj0UBtr9RGRZfRDPQ7sSnuVOLVBSa4UcG75zc/Kn52C/YrZ7t5Wud/oFy03eTiYm5Le/8RED3S8mkFjhqB85kjf+M3lsVTmq8YK4dBOiG0P8rPvIIZaGq9582rADEdk/5oMhz4Dk4vF5IHXWyFq0WDBzsQsNF3+b4RfkF/G7fLcxKIPXQ26qtljzBf4Zfgm1zF6xBjJS7y33Coe6Puja48t4RoiBPVyJs8ztnKmf2rv/15KdnFx1O72Pk7P5rexEf9UB6Yk7bIPEV7lObdXl+lrMXZD49EmPSdSCCTKJO1zyJFTnMt/FkzfxPeBOUZ9SBHt0kUAavG1rvX3pWJu8whRNLNXSDInlP2wyTmwc5k524m3WHwisM6YmXe48/+tRhzpZAP/nlM18AO9DCYwTadNDCjh21AA64qqkRkruu4Wrg78wOZECh401WGv5vBrGEcX8TYyBr3wABJ89IT32yEZha0A6pLkZRJQW0nfisrp51ISsUkP6lr+3zgr50z7jBB8eUvS2KpyYNxLXIclSxvY9NZEViHV7DWXwBOi75ugkRNSPaStfZVLGFkfraY6QfvzR1tSgmaKyEeRG8oI/KaSnIs1ggdnGafLG0FRO8Od37ioAj4OnHjREWe5uAVaNz8K8JB6hu9Zg2277/0/sIFr1Mhs/mzaRYfMuEmrpaB9eEdH0dfvJHwHLdXt0bQ4Iz8iwF+bs=
  template:
    metadata:
      name: ha-mcp-secrets
      namespace: ha-mcp
