apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: open-webui-secrets
  namespace: open-webui
spec:
  encryptedData:
    OPENAI_API_KEYS: AgBbV4xQk+rvyMGh2GECHEkpGWkAPiOYS80ItYEl2blfrBBU0jPYuIGtmtCZtZXE+ufQPGevX31HsbyxIrzhIYI5yvDS3GrkfAYyIK8mEg+05P//vw1LnPh5+vj7e2qmDPt849Hp8dSu4vN1sb65G60Il7J6EnlkT1KBq6pSMf++MwstpXOu6tusVMcv1FkegR+o0KB8W+/9JUzabj0SY4Qgs6rmUBa5JSXcsWMV9M2QbNAn6jgCLSUW88DUdOp9QdRJ7kN5P74/xjZS87IY8eziPNjE8fJQbO1ThGXt/UWa8IKqRe1HuuDYCpvHYXgO4Uk2lgBeXkCGRgw7K6LMFkDd4dJlOQTsJqj328ereJJ5GydXYHyq0DqRFOQmvtWXtrtARLXRQvxpOXGj/xV1jQgXivvtEBXCZ9lrHvqROQUiKbWwAJrx25d4QZ5+qW1wWepVhTxlYdxng/8cJ7SURu5RZtGTdYMzEutsb/E67QRoQYkleYvlOHQnRL7iycH19AvmZis9PKCVC1/vTx7i8SsWGzpi983n/DQn8R1f2T/247Htvqmy3QFSDwf4j8JcM3e6FX5m0AAjn9j+AJKVpISe3HPpN5zaahAbnWBBfNdQf3wND8A+XcrB1C4ER6EoxrGW7tlADVywEYzBM5oCy1P7VxcgrS+28YCtp+OtT3eVALFfpEDm4T4XSjTqtaWE07wKHW8wgGA5hZKoX8s2oXYGf8QhtnVqps+HWBoCVaQyM5KYoBTgbMISfn5XO5tO7fq5XpKXFbs5BLilx5EWLJudB7F8eq4eWzTa5BFkGcDs7FtLVLrJ7bEw/DyiGILpGgft68jbilpPIkkPRm5uZI6aj7QQzbTNfkPxi0COvKQH/kGo1W0ROCHL0DO3oXLdhvCnLEqz8l24uxeXIjBcbjlt4AhYiT8ncCTi0A7nYTcIP1U4hTfyrc/gBovPgNSDVth2Fp4uho4MoBwnAaC6DQ==  # yamllint disable-line rule:line-length
    WEBUI_SECRET_KEY: AgCpiik2g3/c7G6Rev5t2LLsHb4WIq2g7EkJkmHuHjgQzjvGPdFRoNq7cbtBVV7HBghzZ8Sz72tFj+dA/JLPjvJpZqyoWiju1w/9ISgy4+RtrJ9XrGDMcsiWwpC2X/E4+f0hT8ZZFj0wX1Mcnfuhd0Tl13DRl1Zkk+abW55WGSSeYREg/AbRrCMBVFqFbwzrQfltzP8bMSE/cjnG+dqi8mNkYhgZ2fYbjsFuFv681VkK0U3+SiZRfy/8Nk7S21kYf7I0j6CUkb3N4uC2bBloT6YcG3qIZbcPhPIW7YRU+6NvsKh/owMWzOAht6btu9YGgDAveUhSv9Uc3NbUPD6jUe6Mb8yW//2vjvGWijuETFl0pBGvig1Ihc8hgxqAXEkwJfTUJZqzTXxwE1fHT2cjAOyH2sJsDkCPXQTHpq1c+sSUwTwWUUdkrv5qmkTCyfDw9xS1G7JcwN5jKaLGCpmK1p8bL5xceeARFcMKKXm+jJSK8riFdL3MVulX/Z5oHrtifbw7GPha5BkndpP/286HEovVrLIj8AD3qCBWqrGO00yQ9/5XOfzyY3kblsAxEnVk+LjLgQts0XskuCecNev3G4FLPO7uZ9++yVJRkce6i/aRhOJDBpThsjOUY/BCbUIpwHR3ChUV1TNbzKCGYNH0wALvNLstOVV54KqKoXSZuL1Nzc62nKhZNWMzev7IFkPZxf6vC+6zqjekl13fkqjzcsEex7HWfmkaHh48chnqvPWHLOUYB4nLxJKRO3UVYicmWnwhoODDIdL5GVhO3uSWZdnn
  template:
    metadata:
      creationTimestamp: null
      name: open-webui-secrets
      namespace: open-webui
    type: Opaque

