---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: open-webui-manifest-apikey
  namespace: open-webui
spec:
  encryptedData:
    OPENAI_API_KEY: AgDZoAMySFXpxddt446XWlLgj4Sbzs0IvLfsCasG+hignPRJkuURwz1wLXLUxNGeJpF0pfGrVV4VxNNcM8GaAcUuw3TiwRC6ZpX+RcW805evTxFaG4o/YmAzOYQVR3kPASUDNdGYgyXDt3n2JsFnsVCXFRgM6gk2ncwFxiAD1Jps0fgo9Kzgrvzctb0I7OBOzAhj+1NQoXKc9SdRguEY4oRGncSJqhjTL355csP8S3RgYjIwIIM5PWKVMfNnwPhCMSKIRa0q3tkQBgtKi9XIcSJHHf3sUm8CE63GOX0BJ/bjjarJD2o/gtUfuoR82FJB5ML1h8Vo1fCSfRF7CKMWmvfWuY+Flhfm38uDRF+dE30a0XE9XZSKMWEw0hf+v19uTksiA2ofecRsuxUnaTIYNzCdxW7kd3a+odMfeUfWKdOOKzxoY8vrvDy2vTikBpt0quJQxuNlvm2upPjcS1tgTACflXJr41RIcfk9NAEIt6PV7LolqfBWjDZ+3V8xywPIdw+ra8X5887Afon0dgt8F6Mj+U4TqmoX7lZvHGnllGOQcEeahSMifHUhMyNx4Z4JNR7XGV5E/u2EjBPS1YwXhSnBUrbWxIdyzlyIaOxyD9ZKO+p8LCGNGCl2hfZe+fst2+tsSwwZu6d6AJzhKzbJPT+o64yV6h38K1SpapVvImb50iSJB42C7YIuOSW/wjGw6xDrTHWblGS6G9Wjh9t0iFEnmzZctbfgT2PySsBeaMO2QTL6wE9ow3L62PnCj1ux5hgH
  template:
    metadata:
      name: open-webui-manifest-apikey
      namespace: open-webui
