apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx

resources:
  - namespace.yaml

helmCharts:
  - name: nginx-ingress
    releaseName: nginx-ingress
    namespace: ingress-nginx
    version: 1.3.1
    includeCRDs: true
    repo: https://helm.nginx.com/stable
    valuesInline:
      controller:
        setAsDefaultIngress: true
