apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

helmCharts:
  - name: intel-device-plugins-operator
    releaseName: intel-device-plugins-operator
    namespace: kube-system
    version: 0.30.0
    repo: https://intel.github.io/helm-charts/
    includeCRDs: True
  - name: intel-device-plugins-gpu
    releaseName: intel-device-plugins-gpu
    namespace: kube-system
    version: 0.30.0
    repo: https://intel.github.io/helm-charts/
    includeCRDs: True
    valuesInline:
      nodeFeatureRule: True
      