apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pihole

resources:
  - sealed-pihole-password.yaml

helmCharts:
  - name: app-template
    releaseName: orbital-sync
    namespace: pihole
    version: 3.3.2
    repo: https://bjw-s.github.io/helm-charts
    valuesFile: values.yaml
