---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-password
  namespace: pihole
spec:
  encryptedData:
    pihole_password: AgCVtUCETTGxHzNF7DkGk9axURdQBObbkIHPMPgzoH8vjdkjGWNIPnQFaISvl4jo6LvqmlMsJJ0dLIfSWgfbL0xW9okH1IOtwDFgfRqrgzMO27KPCAKZYqUfnpI2GAq0/BstvgFHwpu969uLmBFxjmqMFX9Z7/wKjY4P6HiJJyFRqmFeeNU/KsoVlVAE6a0L3HXIkpYlqd1VJuXrCgw6qgGgx2tDwphVNF8pMB1KqYZq+1e6uLFI4YCTKNOVxa3o8KQAz/z39bEyWIAuR7sslmmqeflFqQw0zpbcsGoJho6gsmw3v5F/UxS3jW430X2PlFVU+OJgrniBDiaWTysxkkYYIstBe3naxJUKvrFV1u0rp6x9bYezR1qBiewcEpRZAXC9l6URMhw5rF5O04CJ4PbWcPI1FxzDD5CQX6vtoz7n8GLe51vbo2O19GoPOyXQYdd/mL0AZBJzJgcwj+VV7JDTHWsDhG1nLNmhDa1TB5T4whvgesOR7DTHYGXB6tAOTyYLzvylMh5Q1X/uua3aYczykDfirChNXDVdv/NsRrcjr0TF6gBamNgWKSYaEHyCU98svrUfYrGgnhknx/wzXS/e7EOcf/QRNnCe35J8AsJ1M+DEtztphUMkhrFo2zVClasw/nepis3VXI7UzV2BcjdCHjr1OTh9Jj2XeLHcL+8DVJLR3CXa9SvEgIYa4PwGB5spX10EJmdako0Z
  template:
    metadata:
      creationTimestamp: null
      name: pihole-password
      namespace: pihole
    type: Opaque
