---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: spotifystats
  namespace: spotifystats
spec:
  storageClassName: freenas-iscsi-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
