---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: spotifystats
  namespace: spotifystats
spec:
  encryptedData:
    SPOTIFY_PUBLIC: AgA2kGgs7coNSNQ7mL9xaKgNWX6u60DzxotiP+mxg8D7m1GAqNanE3LicKw1628BYwgweiN9ggQG2z8zXR72ZBTdd5Qn0dyMnlEgz1P3sUGVQ2QwDjAUKbJg9BniC/p0U5Ar0erxG/ebk4EzVdqZ4uAzv2L6cMr2ROMTxCAkQOeEsDZVI/EF+Pl8HIpi0GVEe5+kc2HfgLXB/fxf4ZaRvvKF3FJg6cjQtVhC9pkF0hhINM+/CoWBX7bKdTrOgyPyCcl5To1Kh3DWrc5B26pGWuc2R6kxuuSSAlynKyoEwRXazQ3ynlynrvg9l16GPZSdCOPaEkz6YDnNQX0Uy7dwebFDI4ghrWzeDYosJAbZYBwxfN0AqbtVleb/DEO5nHrKMBnzKX1DqPQnGqGBDFxwqdBlDGXjlAJDJ4tI7vkgPJGHtUiFis/4rA9FeLhYubEQf5NhlItif2kyClXlbRZ9pIJSHA0mD4vW9phdRzt6OwpeLDx0GLTrR4J/l1ue4hQY3qfEQ2NlM+irzG+q0b/DUBAqYU8I8F7JqI8Jgjbmbbjrd4FrhWiEYudzGE1zgnH8SQgf22RhDBIdr3GfUSWk+X9dW67JoB1XGfNNYLD5HEE+AP4M930/FuEFg+/BqVAHh0Evoko0pa3tSotszSsnVzx0d7PvCDY7UnBxhx1ek8NQ32BrDijV2GJ8RlO4l1tIeiiPaTy5CpxlD+9h6UF+AjJq3Q3His/htNn8kA++H9Dxig==
    SPOTIFY_SECRET: AgCoHzOrrtBCW7OfYgfpRv1USlicefZ1ohJGREpnbquwOjaXRphRxV3JnV6l501b1TPf0RYrOYImD6YWqlR/HzjaAopnja0ivI+kO2p+za1xUOSX/892PqpUndr3FR8DNdARK9c4CRCafxJoF2J1gKpNOteeIgCf5KnMqxS++qFRxfUXXb+MGk91YTxjEToA0h38XC8uhc7XF2JJxY4I2wQT2jijLH2kXI0ThndlkBXiJw+iIutWhMI3yaJMrqWEg829+3V2E9HUo4z6HtsZDEcce7bu8CK8pj4hvVSq8XZM2bfD0HsRL4qAeCmPrzrgixNjzlKxWMibxZiGORP1c9TZ6M2KeF3qHS/u+lBx3jlI/aN+kFIEAwmTBSb8mR00VBK6uYjn/Ioz/94r48SLL7HY2FUnHETHvazNVTSIiZo35kpK9qGbNae3f/x6Gcrsaxbe38/1WAr7vOLi5/ed9aQ6+1651T2NvPM71enu35n39GZF+GzHAN80TizSagyrJmtN5gu3hijJVAuBwO1TTD6A2D3OixNc0Pdrmhnl06L827R7u0ECNvRNfMgGlBdjgxcS3yQlHrigYiGDtrntyrL7n9PTv3dj9TQWFPF3jQUinWbcqrNtoHRfgGvW8mq6Sw66THwiRgX6z2kSjmhmTqKQeehNuoYKpZ1ccj6I88guEEl3GJv60Rdo8laR+EMcQt+NKJDdDM4lQaAv1hkROTJ36399WmHIlQyqgaCkT9L8Aw==
  template:
    metadata:
      creationTimestamp: null
      name: spotifystats
      namespace: spotifystats
