---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: spotifystats
  labels:
    name: spotifystats-mongodb
spec:
  ports:
    - port: 27017
      protocol: TCP
  selector:
    app: spotifystats-mongodb