apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

helmCharts:
  - name: sealed-secrets
    releaseName: sealed-secrets
    namespace: kube-system
    version: 2.12.0
    includeCRDs: true
    repo: https://bitnami-labs.github.io/sealed-secrets
    valuesInline:
      fullnameOverride: sealed-secrets-controller
