apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wfs

resources:
  - namespace.yaml
  - postgres.yaml
  - deploy-rbac.yaml
  - sealedsecret-wfs-secrets.yaml
  - sealedsecret-wfs-adminer-basic-auth.yaml
  - sealedsecret-wfs-ghcr-pull-secret.yaml

helmCharts:
  - name: app-template
    releaseName: wfs
    namespace: wfs
    version: 4.3.0
    repo: https://bjw-s-labs.github.io/helm-charts
    valuesFile: values.yaml
