apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wfs-ghcr-pull-secret
  namespace: wfs
spec:
  encryptedData:
    .dockerconfigjson: AgCZyEg2LzFAi6abpKq7P5NfUSTLsjbOrzM2Yq4yRb3xF3UK7+Ts5f080/Hwzqqj52rJz452hLsUXDstH+xRm7MUVbR5idkuTdmJFciM3/nDL7UBWiC1wU0s54eTz+R5pLoIaliT6hdR4i0kIUK2PdNP8xTbJIpEIBADa/sJEvgXUaAms3OrMEe7O7R/sJTxYUjNgCdVZK7S7lCJI0ovEK6MoN1Stigsjg+rnMfyE8xVTeCre95JLxc7I79OcRUGkpx8xEPeD1/2bj0KFqnbFAoCaQbFw6uC//Bx8i70DBwTmhhNeqhSSVZbvEyP0HCbz4qYpaAGYLlq3gc1EvJc3IPDRZW8RQ7CUBBw1ehRA5RqPQ/JOdO8C2YhOdVk4Os9DF9ch+6JtgcE4oEC8s1KRmpmU9gvHWlrHTR0SrUVwfkcF/h1FnMmc2+iXjygi3IswYMrP2x7aMnUJ5++Rip+VLlY06Su1zXH0qLyGNRxTxgyIyCa0OsmqpMVLfMxBbE37g2eDmUZqaUTYHEm4AnmHarqci1jgeAkapSh03F7QXDxz/FvWbxu71nfk19TdDoiyBS1JVvugR12/MWSHCKyOwA+T9ccBbjvxALKXzlEuzIQHs2j2p42xVChBIc+pxAUywyTx0x7ph1JrZbBxgYQzL+7ysiUlcgDWCJXxdky2TceHpPtQJZqazSLhLVDQlw3TSKMR9CFdOgx67nBlQoI8xc3B3KmPwBLUCxycJUQ71HdRaax3Nzp5sYvnfwtf84gheng6jlf2tzlvHX/Ac4oeA+L4eJmXiZQEdlU702iRXeDcLqtO2RoOh1VtRt/nOFI6/zyVbF1acKf/mdil7sYlLdYZI5IDQqJAJAnoZtlLp6xPO559Sc0cSVBFo0389Zhe4/1en+tualyvGDbhXbukyugyqWahTEBLyYURVw8AYtdW333QXwMtLyKgMlIFwje10Q=
  template:
    metadata:
      creationTimestamp: null
      name: wfs-ghcr-pull-secret
      namespace: wfs
    type: kubernetes.io/dockerconfigjson

