apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wfs-ghcr-pull-secret
  namespace: wfs
spec:
  encryptedData:
    .dockerconfigjson: AgARFL96dG+jWNq1iMx+/jzHw3ppsaFxip07amkTWtijg6wv6Lnhl2pQgL7PJhTf4DN/8sXQFEy1JSJOiMqK9yBppjTPNsUwb43t9jjgQyuvY1CqXiixjT4xbOfl2O7WXbjaAO5jUcDC3bA70LfrnQX85yMr+d+eTdB9U6G0Kb3vZz+WgZ8q5qH9gUI8FZsbNX8JKH5VUrO7MXnPYnYEQ3xed4P1jqLKYeEFg7NRDrkEdVKhH3U+MPLuaZF90YuXQvT1F8Wal1Igb0S/VJTyNEMNfCd8gHGeN1//MH1efeS+A7aQqdvYybx0lxVmATB05ZNtuMV0BCcovqg1/4sD0UnsBz3NMshH1nyecBczpFNx/gihjSzcyNsV2vGoY337e9JZrjieAqnijVlrNia+/zYHLH7nQK4BcclwuC/kQcxq+QSA9zXdgUszmGJbrOUapPRDaLRzNAxM3JgeMxZFar6zOKspTMxkhb+7Ryf0Rl0f2Gujucw5GkdNRTI+GmQdyCWso1mH/4FU4D9+6WmnpLnKval3vEy9QmMmemn/ZckJaY+M+bISIO+1ak84UMZ32C4EE6CbBytAbw870lzlJ/kTsJuSRrplgKwlNV5NVU0ROCMQxznoc4NJefaSs7zsbrulqFyDOh5aYlSso+vxKp2jgORdFteLYyIOPYoEEZkAGXUvuupbEknD/kRjMkEpG+PLtj+0sc/5OZdOQcoaZwhwjZ3C6MIGNejSHlRh/8jNrxD2xu7NpGlXswOeoruP4jruwyN+lmbgSXsskzaIGHPPXPuijumhHh/WCw5dId8L2VH3nx8WANIDEjD/DAcZUNSscvjvtLhO4+MTX9cm6uWzUQrZ44FfH1DpJEHXSiHhXfu9T4+MAhLbfh70z1tYsSgVND1ndyYhC2tKzTEdFYPGh7qwd9aFFin0FriXzzed7zZaiY+PHIWzfn30AFpkMSc=
  template:
    metadata:
      creationTimestamp: null
      name: wfs-ghcr-pull-secret
      namespace: wfs
    type: kubernetes.io/dockerconfigjson

