apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wfs-adminer-basic-auth
  namespace: wfs
spec:
  encryptedData:
    auth: AgB+iNkO1hhwyduxh0FE5i7YnudxavZEjaQpIuf1J+82ETx4rIsZ6J290uaMbXR4oXBbKXup9yXZcyiEb2gh7/smnyOOVj7XkIjV+Sh9HmpmORj/hdnZMlrinn3He8SMDoslrSb1wE2Z2fjWBzvao+qa+Sn8meIYtMvnI4LYjY5sdF4ChTpxlCvE8lu6a94zGZ7iQbrYHXqpyDSE1hSRVl2M/cTuphX6952hmYAXaW04EIuz4+/tef11x3mqxlBReDNaPlJ6LZ5nVucdGRh477RKmXUiJKwTLR7xKLudbhsZjv/SOyNWZgOZUHOBBxC2iwC2wwI3icRwM0Ym+EQ7qqC0qylVS62a50/00Jhy1VCgEBOp+2iNLTbidh0/OnnqlHIxJXWPGzyoBmbdQfHHKN+NaF4v0pV1Js8QC2WMTwyNVLE2sHcWV37z0Y/+zuWHL3zd3r+RXsrSd7Xs9kap6oITLdizTcUZaOrySuzHqcdHoYStuSaYGZVu2T1Ff4ALg64DHwBJuwIkWMktETz0e3uKx47PyttWSzKRp28F/wdAQkbqm0aZ09dPeXLcqz+gfTZf4FH0HUYWBGzAdV24I2td8+Tu9hRddV7R3+jP1B6q1M8a2aVWKsQTDdHNf88RhEHkmRcFNrXnewzlzO2uU6bMvEyJDp7OpNIMqh+ynD2yrewOyuhLniLetRmjw6hs2Vrwqb7u9AeLeE3ofHyPo/3L0caSCy+MVTOkwKHtd9ippui82gaEmDtzjnAtKUBVOZi6dWTIGpIlr9WtqHKyZ9EiHMGTTg==
  template:
    metadata:
      creationTimestamp: null
      name: wfs-adminer-basic-auth
      namespace: wfs

